### ISSUE TITLE
Please change font which is Multilingual support.

### ISSUE THREAD

**Issue by axsann** [gonum/plot#208]
I'm Japanese.
NimbusRomNo9L-Regu.ttf is only support english.
Change the font please.

**Comment by benoitmasson** [comment]
Hi,

I can't display asian characters either… what can we do about it, is it possible to enforce another font file?

A basic plot with title "aa 漢字 bb" gives me the following result, in Helvetica and Times-Roman fonts:
![chart_helv](https://cloud.githubusercontent.com/assets/10956459/24969048/b8fd9baa-1faf-11e7-96fa-c42a5dda73a0.png)
![chart_roman](https://cloud.githubusercontent.com/assets/10956459/24969049/b90cfa3c-1faf-11e7-8aea-a61bd289f6b9.png)

This is a serious issue I think… I'd be happy to help, but don't know where to start… do Liberation fonts contain these characters or is it an issue with support of these fonts in Go?

**Comment by eaburns** [comment]
Fonts have been a constant annoyance since the beginning. See my comment on 29 Mar 2015 in #190 for a description of the problem.

That said, if you don't care about pdf or esp (which are decreasing in commonality the days — does anyone even know what eps is any more? did they ever?), then you can use whatever font you'd like. Though it's been years and I don't quite remember how. Maybe vg.AddFont? Hopefully someone else here can help.

**Comment by benoitmasson** [comment]
Thanks for the answer, indeed I see the where the trouble is…

I'm only exporting to PNG for now (and yes I used a lot EPS, a long time ago :-) Supporting it may be questionable nowadays indeed, but I think PDF export has to be maintained… unless SVG is considered sufficient for vector graphics), so `vg.AddFont()` sounded like a good option. It did not work at once though, since exporting to PNG uses `vgimg.FillString()`, which in turn uses an internal font map…

So I hacked the `vgimg.go` file to add a `vgimg.AddFont()` function, which in the end calls the `vg.AddFont()` one (the other way around is not possible since `vgimg` already depends on `vg`, this would lead to an import cycle).

This is not very smart by if anybody is interested, I can submit a pull request for this patch, so that in the end `vgimg.AddFont()` does the job of adding a new font for texts in charts which are to be exported as images.

**Comment by sbinet** [comment]
@benoitmasson I don't think that's the "correct" way to go.
`vgimg` should work with `vg` (and its fontmap), making sure the `vgimg` internal fontmap is synchronized with the one from `vg`.

ie: when one does `vg.AddFont("MyFont", myFont)`, then `vgimg` should be able to use that one.

@benoitmasson could you post somewhere (here, or via a gist) the program that generated the plots above, together with the fonts you used?
(I might give this a stab later this week)

**Comment by ctessum** [comment]
draw2d, which is the backend for the vgimg backend, also has a pdf driver: https://godoc.org/github.com/llgcode/draw2d/draw2dpdf. Switching to that instead of bitbucket.org/zombiezen/gopdf/pdf may fix the problem for pdfs.

**Comment by benoitmasson** [comment]
@sbinet The problem is that `vgimg` uses an internal (hard-coded) font map, and the package already depends on `vg`, so updating this map cannot be done from `vg`…

I agree that `vgimg` calling `vg.AddFont()` is a bit weird, but did not find another (easy) way to do this. There are probably smarter alternatives, like having `vgimg` use `vg`'s font map directly, but I don't know these packages well enough to figure out if it's reasonable or not.

Here's the code that produces the charts:
```golang
package main

import (
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/gonum/plot"
	"github.com/gonum/plot/plotter"
	"github.com/gonum/plot/vg"
)

func main() {
	for _, font := range []string{"Helvetica", "Times-Roman"} {
		w, err := draw("aa 漢字 bb", font)
		if err != nil {
			panic(err)
		}

		file, err := os.OpenFile(fmt.Sprintf("chart_%s.png", strings.ToLower(font)), os.O_CREATE|os.O_WRONLY, 0644)
		if err != nil {
			panic(err)
		}
		defer file.Close()

		_, err = w.WriteTo(file)
		if err != nil {
			panic(err)
		}
	}
}

func draw(title, fontName string) (io.WriterTo, error) {
	// Initialize chart
	plot.DefaultFont = fontName
	p, err := plot.New()
	if err != nil {
		return nil, err
	}

	// Set title and font
	p.Title.Text = title
	font, err := vg.MakeFont(fontName, 12)
	if err != nil {
		return nil, err
	}
	p.Title.Font = font

	// Fill plot
	bar, err := plotter.NewBarChart(plotter.Values{1}, vg.Length(10))
	if err != nil {
		return nil, err
	}
	p.Add(bar)

	// Save the plot to a PNG buffer, ready for writing.
	writerTo, err := p.WriterTo(vg.Points(400), vg.Points(300), "png")
	if err != nil {
		return nil, err
	}
	return writerTo, nil
}
```

To make it work with Japanese characters, I added this at the very beginning of the `main()` function
```golang
	file, err := os.Open("/usr/share/fonts/opentype/ipafont-mincho/ipam.ttf")
	if err != nil {
		panic(err)
	}
	defer file.Close()
	ttf, err := ioutil.ReadAll(file)
	if err != nil {
		panic(err)
	}
	font, err := truetype.Parse(ttf)
	if err != nil {
		panic(err)
	}
	vgimg.AddFont("Mincho", draw2d.FontFamilySerif, draw2d.FontStyleNormal, font)
```
(Note that it uses my `vgimg.AddFont()` function, if you want to go for `vg.AddFont()` directly you will have to edit `vgimg.fontMap` by hand).
Then added `"Mincho"` to the loop:
```golang
	for _, font := range []string{"Helvetica", "Times-Roman", "Mincho"} {
```

The TTF font file may be downloaded here, for example: http://http.debian.net/debian/pool/main/f/fonts-ipafont/fonts-ipafont_00303.orig.tar.gz

**Comment by kortschak** [comment]
I'd be very happy if we didn't increase our dependency on draw2d. I cant think of an API stability issue we have had with bitbucket.org/zombiezen/gopdf/pdf, but draw2d has been a significant moving target.

**Comment by sbinet** [comment]
after some digging into the `draw2dimg` code (and I agree with @kortschak , keeping our dependency against `draw2d` as much as it is would be best), I feel relatively confident that the `draw2dimg` package doesn't make (much) use of the `draw2d.FontData.{Style,Family}` fields.

we could thus let go of the panic if a given `vg.Font` isn't in the `vgimg.fontMap` map and lazily fill it with:

```go
data = draw2d.FontData{Name: font.Name()}
```

I have put something together inside my `multi-lang` branch.

**Comment by sbinet** [comment]
here is what I get:
![chart_mincho](https://cloud.githubusercontent.com/assets/1070920/25398313/d15202ea-29eb-11e7-8909-22d73356bb5d.png)
![chart_helvetica-boldoblique](https://cloud.githubusercontent.com/assets/1070920/25398317/d7500e08-29eb-11e7-8404-bfa3f388574a.png)

with the following program:

```go
package main

import (
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"os"
	"strings"

	"github.com/golang/freetype/truetype"
	"github.com/gonum/plot"
	"github.com/gonum/plot/plotter"
	"github.com/gonum/plot/vg"
)

func main() {
	ttf, err := ioutil.ReadFile("IPAfont00303/ipam.ttf")
	if err != nil {
		log.Fatal(err)
	}
	font, err := truetype.Parse(ttf)
	if err != nil {
		log.Fatal(err)
	}
	vg.AddFont("Mincho", font)

	for _, font := range []string{"Helvetica", "Times-Roman", "Mincho", "Courier", "Helvetica-BoldOblique"} {
		w, err := draw("aa 漢字 bb", font)
		if err != nil {
			panic(err)
		}

		file, err := os.OpenFile(fmt.Sprintf("chart_%s.png", strings.ToLower(font)), os.O_CREATE|os.O_WRONLY, 0644)
		if err != nil {
			panic(err)
		}
		defer file.Close()

		_, err = w.WriteTo(file)
		if err != nil {
			panic(err)
		}
	}
}

func draw(title, fontName string) (io.WriterTo, error) {
	// Initialize chart
	plot.DefaultFont = fontName
	p, err := plot.New()
	if err != nil {
		return nil, err
	}

	// Set title and font
	p.Title.Text = title + " (font=" + fontName + ")"
	font, err := vg.MakeFont(fontName, 12)
	if err != nil {
		return nil, err
	}
	p.Title.Font = font

	// Fill plot
	bar, err := plotter.NewBarChart(plotter.Values{1}, vg.Length(10))
	if err != nil {
		return nil, err
	}
	p.Add(bar)

	// Save the plot to a PNG buffer, ready for writing.
	writerTo, err := p.WriterTo(vg.Points(400), vg.Points(300), "png")
	if err != nil {
		return nil, err
	}
	return writerTo, nil
}

```

**Comment by benoitmasson** [comment]
Removing `vgimg` font map looks like a great (and simple) solution indeed, thanks for the quick patch.

That will do the job for me but as mentioned in [this earlier message](https://github.com/gonum/plot/issues/208#issuecomment-293743039), the issue may not be solved for PDF/EPS exports. But does anyone need them?

**Comment by sbinet** [comment]
if somebody needs that, we'll try to address it :)

**Comment by sbinet** [comment]
for PDF, we may want to switch to `github.com/jung-kurt/gofpdf` which is what ajstarks uses for his `pdfdeck`: https://github.com/ajstarks/deck/blob/master/cmd/pdfdeck/pdfdeck.go

`gofpdf` seems better maintained (`zombiezen/gopdf` seems... dormant.)
