### ISSUE TITLE
Plot generation fails due to missing fonts in production (Dokku)

### ISSUE THREAD

**Issue by esantoro** [gonum/plot#213]
Hi, I am using gonum/plot with codes very similar to examples.

Code works reasonably well on my development machine, but fails in production (Dokku/Docker/Ubuntu 14.04 LTS):

2015/08/04 06:33:02 Panic recovery -> Failed to locate a font file NimbusRomNo9L-Regu.ttf for font name Times-Roman
/usr/local/go/src/runtime/panic.go:387 (0x412f08)

How can I solve this ?

**Comment by kortschak** [comment]
Try setting the VGFONTPATH env var to the location of your fonts.

**Comment by esantoro** [comment]
I am trying 

    VGFONTPATH=/usr/share/fonts/

**Comment by esantoro** [comment]
For the records, that did not work. I solved by following the following steps:

1. Find the name of the missing font by reading runtime logs (dokku logs <myapp>), in my case it was NimbusRomNo9L-Regu.ttf

2. Find the actual position of the font on the containerized application: run /bin/bash in the context of the container (dokku run <myapp> /bin/bash): 

    find / -name NimbusRomNo9L-Regu.ttf

in my case it was:

    /app/Godeps/_workspace/src/github.com/gonum/plot/vg/fonts/NimbusRomNo9L-Regu.ttf

3. Set the VGFONTPATH environment variable:

    dokku config:set <myapp> VGFONTPATH=/app/Godeps/_workspace/src/github.com/gonum/plot/vg/fonts

So it works now. Thanks.

**Comment by kortschak** [comment]
Thank you for the feedback.

**Comment by esantoro** [comment]
Thank you for your fast answers. I would never have guessd of that environment variable.

I thing you and the other developers should really focus on writing some good/better documentation.

**Comment by kortschak** [comment]
At the moment our focus is on getting the API to a state where it can be stabilised before plotinum goes off line at the beginning of next year.

To find VGFONTPATH (I've never had this problem, so I didn't know the var existed until yesterday) I just looked through the code path for font failure (partly from experience in the code base, but otherwise the complete stack trace would have done). This is the joy of a source distribution.

As far as docs go, I think they are actually pretty good, but specific improvement suggestions and PRs for improvement are always welcomed.
