### ISSUE TITLE
Error when trying to produce plot on windows

### ISSUE THREAD

**Issue by ebusato** [gonum/plot#244]
Hi,

I have a software producing gonum-plots on ubuntu and it works fine. But when I try to run the executable on windows (I create it running "GOOS=windows go build" and then scp it to windows) I get this error :

   panic: Failed to locate a font file NimbusRomNo9L-Regu.ttf for font name Times-Roman

I'm not sure what the problem is. Is it a problem with the windows executable I created on ubuntu or a problem with my windows OS that does not include that font ?

Would you have any idea on how to solve this problem ?

Thanks,
Emmanuel

**Comment by sbinet** [comment]
this is because the machine on which you are trying to run the cross-compiled program does not have the requested fonts installed:
 https://github.com/gonum/plot/blob/master/vg/font.go#L241
 https://github.com/gonum/plot/blob/master/vg/font.go#L34

when the program is run on a machine where `gonum/plot` was installed, `initFontDirs` is able to load the NimbusRomblabla files from the source tree.

2 possible fixes:

1. install `gonum/plot` on the windows machine or,
2. only copy the files under `gonum/plot/vg/fonts` under some directory and set the `%VGFONTPATH%` environment variable to that directory.

Feel free to reopen if you are somewhat dissatisfied with the explanation :)

(PS: this is essentially a duplicate or close cousin to #107)

**Comment by osullivryan** [comment]
Is it possible to build with the font file saved as a []byte as stated on another thread about this? Do you have any experience with this?

**Comment by sbinet** [comment]
it is technically possible: https://github.com/jteeuwen/go-bindata (or any other embedding package)
AFAIR, (and as discussed in #107) the issue is licensing.

somebody could perhaps work with (presumably) `golang.org/x/exp/shiny/text` and `golang.org/x/image/font` to perform BSD-compliant font rendering. (I am just hand-waving here, I have no deep (nor shallow) understanding of the issues at hand here)

**Comment by eaburns** [comment]
@osullivryan, unfortunately we cannot do that because of licensing issues; the fonts are released under the GPL — whatever that means for art.

It's possible to use other fonts either by setting the VGFONTPATH environment variable or by directly setting the vg.FontDirs variable. For images (png, jpg, tiff, whatever) and SVG, any truetype font should work. For PDF and EPS, only fonts required by those standards will work: https://en.wikipedia.org/wiki/PostScript_fonts#Core_Font_Set.
