### ISSUE TITLE
plotter: testing is not idempotent with respect to failure

### ISSUE THREAD

**Issue by kortschak** [gonum/plot#252]
Invoking `go test` on `github.com/gonum/plotter` is not idempotent if there is a failure since the test overwrites the golden values. This should never happen unless the regen flag is passed in.

The ideal solution is to not write anything to a file system however this is required because of the use of example tests for the general testing. I'm even more convinced now that that requirement is too hard.

**Comment by ctessum** [comment]
I think the issue is that because the is a visual library, at least the examples need to be visual, and therefore need to write to the filesystem. It's desirable to have ensure that the examples produce the expected output, so at least some of the testing has to be visual-based too.

In #253 I believe I've made the test idempotent to the likely sources of failures, which may (or may not) be close enough.
