### ISSUE TITLE
iplot: interactive REPL to produce plots + scripting language

### ISSUE THREAD

**Issue by sbinet** [gonum/plot#283]
it could be interesting to create a scripting language and/or a REPL to interactively create plots.

possible ideas:

- reuse `Gnuplot` syntax and https://godoc.org/github.com/cznic/plot parser
- expose a `python`, `ruby`, `octave`, ... interface so `gonum/plot` could be used from these scripting languages
- roll with our own scripting language + REPL

**Comment by eaburns** [comment]
Why not just us Go?

**Comment by sbinet** [comment]
for the moment, there is no real `Go` REPL. I know, I am trying to build one.
moreover, even if Go can be easily installed, providing users with just a simple (possibly cross-compiled) executable to create plots is useful (c.f. `Gnuplot`) : even w/o a REPL, it's not (yet) possible to embed the Go compiler inside an executable...
so this leaves implementing a (small) scripting language, or expose bindings to other scripting languages.

**Comment by eaburns** [comment]
I wasn't suggesting a Go REPL, I was suggesting a normal Go program instead of a REPL (i.e., the current status quo). Personally, I would prefer not to embed a second language inside of gonum/plot; better that we encourage people to program in the pre-existing programming language: Go. It's a great language! If we want to provide something interactive, let's make a GUI instead.

**Comment by sbinet** [comment]
ok. I won't push this on `gonum/plot`'s core.
