### ISSUE TITLE
vg/vgpdf: add ability to create PDFs with multiple pages

### ISSUE THREAD

**Issue by sbinet** [gonum/plot#450]
it would be great to be able to create a bunch of plots and save each in a new PDF page:

```go
func plot(x,y []float64) (*plot.Plot, error) { ... }

func analysis() {
    for i, sample := range samples {
        p, err := plot(sample.x, sample.y)
        // ... save p to page-i ...
    }
}
```

**Comment by kardianos** [comment]
(Short backstory: moving many chart report from my normal HTML -> PDF report pipeline due to current PDFer limitations in performance with 80+ charts in a single document).

In my case, I'd ideally want to be able to insert charts as some type of semi-opaque objects in a larger PDF document. To get me through the day, I'll probably need to modify vgpdf locally to expose the underlying pdf writer.  Even if there wasn't a more advanced layout option, I need to put N plots on a single page.

Okay, I know what I want to tackle next: document layout (eep!). That would be really useful when generating reports.

**Comment by ctessum** [comment]
For multiple plots on a single page, you can use `draw.Tiles` and `plot.Align`. For multiple plots that are not arranged in a regular grid, you can use `draw.Crop`.

**Comment by kardianos** [comment]
@ctessum Thanks for the tip. That helped.

In vgpdf, I ended up adding locally the following function:
```
func (c *Canvas) AddPage() {
	_, h := c.Size()
	c.Pop()
	c.doc.AddPage()
	c.Push()
	c.Translate(vg.Point{0, h})
	c.Scale(1, -1)
}
```

This seems to work and might be a reasonable API. With didn't need to expose the underlying PDF writer either. I can send a PR if you're interested. It solved my immediate need anyway.

**Comment by kortschak** [comment]
That SGTM.

**Comment by ctessum** [comment]
Would something like `NextPage` be a better name? Or `MoveNewPage`? Something might better reflect that the cursor is moving to the next page as it gets added. That is what's happening, correct?

**Comment by sbinet** [comment]
`NewPage` ? `MakeNewPage`?

(for me `NextPage` sounds too much like iteration.)

**Comment by sbinet** [comment]
@kardianos : want to give a stab at sending a PR? (I have a colleague who would be interested in getting this multi page feature.)
