### ISSUE TITLE
Export the talbotLinHanrahan function

### ISSUE THREAD

**Issue by chmike** [gonum/plot#523]
### What are you trying to do?
Customize the ordinate axis. I need the axis to be reverted, max at the bottom and min at the top, and I want 5 main ticks instead of 3 for finer granularity.

### What did you expect to happen?
I wished the `talbotLinHanrahan` function was exported so that I can call it with my own parameters. I wish I had more liberty degree to adjust axis as I want. There is actually no way to define axis in reverse order. Not sure I could do it if the `talbotLinHanrahan` function was public by swapping min and max. 

### What actually happened?
The axis label generation is all private and leaves not much room to customization. 

I could copy the code/file, but exporting functions would allow to avoid that and would make Plot more versatile. 

### What version of Go and Gonum/plot are you using?
Latest

### Does this issue reproduce with the current master?
yse

**Comment by sbinet** [comment]
For the invert axis part, wouldn't this https://github.com/gonum/plot/pull/487 already cover it?

**Comment by chmike** [comment]
This is exactly what I needed.

**Comment by chmike** [comment]
I still have a degenerated Y axis labeling. See this example. The Y axis show a percentage relative to the last (right most) point. 

![image](https://user-images.githubusercontent.com/235856/52812136-16aad480-3097-11e9-9e99-16caa639b969.png)

**Comment by sbinet** [comment]
hum... yes, I vaguely remember that it used to be possible to play with the number of suggested (major?) ticks.
it doesn't seem to be possible anymore with the "new" talbotLinHarahan function.
perhaps best to file another issue for this particular problem (with some simple reproducer?)

**Comment by kortschak** [comment]
There was never a way to alter the number of suggested major ticks, it was always 3 since introduction. See [here prior to when TLH was added](https://github.com/gonum/plot/blob/6bb95ddfb04f41c66de73dfb4a2eeebfca2cb350/axis.go#L353-L414) and [here when it was introduced](https://github.com/gonum/plot/blob/6aedb94b1ea2652214222edfb9bf54730c4d55ac/plot/axis.go#L249-L298).

If `DefaultTicks` were make an `int`, then its value could be the suggested number of major ticks (if 0 then choose 3), or a struct with the same method of control. This would need discussion though since it makes a spooky action at a distance possible. I'd prefer to just add another type that does the same thing and has no default.

**Comment by chmike** [comment]
I also don’t understand why I have the .00 after the values. 

It seam that the right strategy is to implement my own Ticks function as I did for the X axis. I apologize for the noise.
