### ISSUE TITLE
Log(0) panic caused by sanitizeRange

### ISSUE THREAD

**Issue by MbarekFiras** [gonum/plot#681]
In case of log scale is used and min=max=1 (e.g one point when X or Y = 1)
sanitizeRange would put the min to 0:
https://github.com/gonum/plot/blob/caab7788e04dfd7a74cec4ee80f55b7d1f9a2bfa/axis.go#L161

and as a result a log(0) panic:

```Values must be greater than 0 for a log scale.```

**Comment by kortschak** [comment]
Please follow the issue template; it asks for information that is helpful for us to help you.

We could type assert on `a.Scale` in that function, but that will only defer the problem to the next case where a scale has an invalid value in the range and so we enter a game of whack-a-mole with a large type switch to condition on the scaling that is used. The API intentionally exposes `Axis.Min` and `Axis.Max` so that they can be conditioned according to the author's understanding of the system that they are creating. So if you have a y log scaled plot, checking that `p.Y.Min > 0 && p.Y.Max > 0` can be done, setting them appropriately for your domain if the condition fails.

**Comment by MbarekFiras** [comment]
Understand. Thanks for the clarification!
